spring:
  datasource:
    url: jdbc:mysql://containers-us-west-51.railway.app:6800/railway
    username: root
    password: XauymfdlKMlXet2RN8av
  jpa:
     hibernate:
      ddl-auto: update

server:
  port: 8082
