spring:
  datasource:
    url: jdbc:mysql://containers-us-west-51.railway.app/railway
    username: root
    password: XauymfdlKMlXet2RN8av
    port: 6800
  jpa:
     hibernate:
      ddl-auto: update

server:
  port: 8082
